### ISSUE TITLE
Suggestion - an option to exclude files from news

### ISSUE THREAD

**Issue by rec32** [rejetto/mark-news#1]
For example, I would like to exclude all files named `"*.jpg"` and `"*1*2*3*"` from triggering news mark

**Comment by rejetto** [comment]
<img width="150" alt="image" src="https://github.com/user-attachments/assets/e11b2b77-4a8e-4f0b-bd9d-731617cd6a93">

i'm going to offer you this option, and you can use the `!` syntax to negate the files you want, [as documented here](https://github.com/rejetto/hfs/wiki/Wildcards#special-characters).

**Comment by rejetto** [comment]
published an update for the plugin: version 1.1
